# Generated by Django 4.2.2 on 2024-02-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('รอดำเนินการ', 'Pending'), ('ยอนรับ', 'Approved'), ('ปฏิเสธ', 'Rejected')], default='Pending', max_length=200),
        ),
    ]
