# Generated by Django 4.2.2 on 2024-02-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_alter_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_number',
        ),
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
