# Generated by Django 4.2.2 on 2024-03-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_table_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table",
            field=models.CharField(max_length=20),
        ),
    ]
